### ISSUE TITLE
using multi select with d3 v5 and es6 

### ISSUE THREAD

**Issue by headwinds** [d3/d3-selection-multi#17]
I like how multi select allows you to style nodes using objects but how can I include this library in my d3 v5 and es6 project?

I imagine I need to import it somehow ?!

```
import * as d3 from 'd3';
import * as d3-selection-multi from 'd3-selection-multi' // ????
```

Ultimately, I want to be able to use v5 and pass in an object without having to use snapSVG:

```
 g
    .styles({fill:'blue',stroke:'#CCC'})
```
I see multi select was part of v4 - is it still relevant in v5?

For now, I built a simple lodash helper to apply the style object to an element 

```
const styleElement = (el, style) => {
  _.forIn(style, (val, key) => {
    el.style(key, val);
  });
};

styleElement(g,{fill:'blue',stroke:'#CCC'})
```

**Comment by mbostock** [comment]
You can’t combine the `d3` default bundle with D3 modules when using ES modules (or require). If you want to use individual D3 modules such as d3-selection-multi, you can’t use the `d3` default bundle (in an ES/AMD environment).

```js
import * as d3_selection from 'd3-selection';
import * as d3_selection_multi from 'd3-selection-multi';
```

**Comment by headwinds** [comment]
@mbostock much appreciated! I think I follow... instead of just importing D3, I would need to import the D3 modules individually...I'll research the ones I need.

would you recommend [creating a custom bundle](https://bl.ocks.org/mbostock/bb09af4c39c79cffcde4) if someone wanted to combine D3 modules such as ad3-selection-multi? That would that bring me back to 1 import, right?
