### ISSUE TITLE
Please make this default

### ISSUE THREAD

**Issue by j-funk** [d3/d3-selection-multi#18]
Forgive me for saying so, but this should really be part of the default distribution.

https://stackoverflow.com/questions/20822466/how-to-set-multiple-attributes-with-one-value-function

**Comment by mbostock** [comment]
Thanks for the feedback. I decided to not make this part of the default distribution, but you are welcome to fork d3 and provide your own distribution if you feel differently. I also recommend taking a look at [d3-jetpack](https://github.com/gka/d3-jetpack) if you like convenience helpers.
